site_name: environMAP
site_url: https://prenner-eo.github.io/environMAP/
repo_url: https://github.com/prenner-eo/environMAP
repo_name: prenner-eo/environMAP

nav:
  - Home: index.md
  - Project Goal: project-goal.md
  - Regions & Cohort Sites: regions-and-cohorts.md
  - environMAP Datasets: environMAP-datasets.md
  - Geodata Access: geodata-access.md
  - Impressum: impressum.md
  - Contact: contact.md

theme:
  name: material
  logo: assets/images/environmental-logo-color.png
  favicon: assets/images/environmental-logo-color.png
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prenner-eo
      name: GitHub

extra_css:
  - assets/overrides.css